# Generated by Django 4.2.4 on 2023-09-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinigai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='families',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='pinigai.family'),
        ),
    ]
