# Generated by Django 4.2.4 on 2023-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinigai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
