# Generated by Django 4.2.4 on 2023-09-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinigai', '0002_rename_user_family_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(default='Other', max_length=255),
        ),
    ]
