# Generated by Django 4.2.4 on 2023-09-16 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinigai', '0002_alter_profile_families'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='user',
        ),
        migrations.AddField(
            model_name='family',
            name='user',
            field=models.ManyToManyField(related_name='families', to=settings.AUTH_USER_MODEL),
        ),
    ]
