# Generated by Django 4.2.4 on 2023-08-30 23:38

from django.db import migrations
import pinigai.models


class Migration(migrations.Migration):

    dependencies = [
        ('pinigai', '0003_alter_customuser_username_alter_customuser_vardas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', pinigai.models.CustomUserManager()),
            ],
        ),
    ]
