# Generated by Django 4.0.6 on 2023-09-26 15:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinigai', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User),
        ),
    ]
