# Generated by Django 4.2.4 on 2023-09-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinigai', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
