# Generated by Django 4.2.4 on 2023-09-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinigai', '0009_sharedbudget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
