# Generated by Django 4.2.4 on 2023-09-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinigai', '0012_alter_customuser_managers_family_parent_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='parent_family',
        ),
    ]
