# Generated by Django 4.2.4 on 2023-09-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinigai', '0014_family_user_alter_family_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinigai.family'),
        ),
        migrations.AddField(
            model_name='family',
            name='selected_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinigai.family'),
        ),
    ]
